// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal class CurProcess
    {

        [JsonProperty("processName")]
        public string ProcessName { get; set; }

        [JsonProperty("processId")]
        public string ProcessId { get; set; }
    }

    internal class NextProcess
    {

        [JsonProperty("processName")]
        public string ProcessName { get; set; }

        [JsonProperty("processId")]
        public string ProcessId { get; set; }
    }

    internal class PreProcess
    {

        [JsonProperty("processName")]
        public string ProcessName { get; set; }

        [JsonProperty("processId")]
        public string ProcessId { get; set; }
    }

    internal class List
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("curProcess")]
        public CurProcess[] CurProcess { get; set; }

        [JsonProperty("productTypeId")]
        public string ProductTypeId { get; set; }

        [JsonProperty("nextProcess")]
        public NextProcess[] NextProcess { get; set; }

        [JsonProperty("preProcess")]
        public PreProcess[] PreProcess { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("productName")]
        public string ProductName { get; set; }

        [JsonProperty("job")]
        public string Job { get; set; }
    }

    internal class ProductInfoApi
    {

        [JsonProperty("errorno")]
        public int Errorno { get; set; }

        [JsonProperty("list")]
        public List[] List { get; set; }
    }

}
